openapi: 3.0.0
info:
  title: Calorie GPT API
  description: API for tracking daily calorie and nutrition intake with GPT integration
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://calorie-gpt.onrender.com
    description: Production server

paths:
  /entries:
    post:
      summary: Create a new nutrition entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NutritionEntryInput'
      responses:
        '201':
          description: Entry created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NutritionEntry'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    get:
      summary: Get all nutrition entries
      responses:
        '200':
          description: List of nutrition entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NutritionEntry'

  /entries/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Entry ID
    
    get:
      summary: Get a specific nutrition entry
      responses:
        '200':
          description: Nutrition entry found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NutritionEntry'
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Update a nutrition entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NutritionEntryInput'
      responses:
        '200':
          description: Entry updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NutritionEntry'
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete a nutrition entry
      responses:
        '200':
          description: Entry deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Entry deleted successfully
        '404':
          description: Entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /entries/date/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
        description: Date in YYYY-MM-DD format
    
    get:
      summary: Get entries for a specific date
      responses:
        '200':
          description: List of nutrition entries for the date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NutritionEntry'

components:
  schemas:
    NutritionEntryInput:
      type: object
      required:
        - date
        - base_calorie_limit
        - food
        - calories
      properties:
        date:
          type: string
          format: date
          example: "2025-02-16"
        base_calorie_limit:
          type: number
          format: float
          example: 2000
        workout_calories:
          type: number
          format: float
          example: 300
        food:
          type: string
          example: "Chicken Salad"
        calories:
          type: number
          format: float
          example: 350
        protein:
          type: number
          format: float
          example: 25
        carbs:
          type: number
          format: float
          example: 15
        fat:
          type: number
          format: float
          example: 20
        description:
          type: string
          example: "Grilled chicken breast with mixed greens"

    NutritionEntry:
      allOf:
        - $ref: '#/components/schemas/NutritionEntryInput'
        - type: object
          properties:
            id:
              type: integer
              example: 1
            calories_remaining:
              type: number
              format: float
              example: 1950
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid input data"
