basePath: /
definitions:
  main.NutritionEntry:
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for tracking daily calorie and nutrition intake with GPT integration
  title: Calorie GPT API
  version: "1.0"
paths:
  /entries:
    get:
      description: Get a list of all nutrition entries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.NutritionEntry'
            type: array
      summary: Get all nutrition entries
    post:
      consumes:
      - application/json
      description: Create a new nutrition entry with calorie tracking
      parameters:
      - description: Nutrition Entry
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/main.NutritionEntry'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.NutritionEntry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new nutrition entry
  /entries/{id}:
    delete:
      description: Delete a nutrition entry by its ID
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a nutrition entry
    get:
      description: Get a nutrition entry by its ID
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.NutritionEntry'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a specific nutrition entry
    put:
      consumes:
      - application/json
      description: Update an existing nutrition entry
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Nutrition Entry
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/main.NutritionEntry'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.NutritionEntry'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a nutrition entry
  /entries/date/{date}:
    get:
      description: Get all nutrition entries for a specific date
      parameters:
      - description: Date (YYYY-MM-DD)
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.NutritionEntry'
            type: array
      summary: Get entries by date
swagger: "2.0"
